### ISSUE TITLE
windows 11 ARM 

### ISSUE THREAD

**Issue by GripService** [OData/ODataConnectedService#375]
### Describe the bug
I am using Windows 11 arm and Visual Studio 2022 from the extension manager, but I can not find the OData extension, I have tried to install it from the web. , it's showing this error 

```cmd
14-11-2023 3:19:31 PM - Microsoft VSIX Installer
14-11-2023 3:19:31 PM - -------------------------------------------
14-11-2023 3:19:31 PM - vsixinstaller.exe version:
14-11-2023 3:19:31 PM - 17.7.2196+2d27ec4064
14-11-2023 3:19:31 PM - -------------------------------------------
14-11-2023 3:19:31 PM - Command line parameters:
14-11-2023 3:19:31 PM - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,\\Mac\Home\Downloads\Microsoft.OData.ConnectedService.vsix
14-11-2023 3:19:31 PM - -------------------------------------------
14-11-2023 3:19:31 PM - Microsoft VSIX Installer
14-11-2023 3:19:31 PM - -------------------------------------------
14-11-2023 3:19:32 PM - Skipping product Microsoft.VisualStudio.Product.BuildTools (4edfebad) since it does not support extensions
14-11-2023 3:19:32 PM - Initializing Install...
14-11-2023 3:19:32 PM - Searching for applicable products...
14-11-2023 3:19:33 PM - Found installed product - Visual Studio Professional 2022
14-11-2023 3:19:33 PM - Found installed product - Global Location
14-11-2023 3:19:33 PM - Extension Details...
14-11-2023 3:19:33 PM - 	Identifier         : ODataConnectedService.e30335d6-f9c7-4d08-b66a-f011f3f18477
14-11-2023 3:19:33 PM - 	Name               : OData Connected Service
14-11-2023 3:19:33 PM - 	Author             : Microsoft
14-11-2023 3:19:33 PM - 	Version            : 1.0.2
14-11-2023 3:19:33 PM - 	Description        : OData Connected Service for V1-V4
14-11-2023 3:19:33 PM - 	Locale             : en-US
14-11-2023 3:19:33 PM - 	MoreInfoURL        : https://github.com/odata/ODataConnectedService
14-11-2023 3:19:33 PM - 	InstalledByMSI     : False
14-11-2023 3:19:33 PM - 	SupportedFrameworkVersionRange : [4.5,)
14-11-2023 3:19:33 PM - 	SignatureState     : ValidSignature
14-11-2023 3:19:33 PM - 	SignedBy           : OData (.NET Foundation)
14-11-2023 3:19:33 PM - 	Certificate Info   : 
14-11-2023 3:19:33 PM - 		-------------------------------------------------------
14-11-2023 3:19:33 PM - 		[Subject]       : CN=OData (.NET Foundation), O=OData (.NET Foundation), L=Wakefield, S=Massachusetts, C=US, SERIALNUMBER=603389068, OID.2.5.4.15=Private Organization, OID.1.3.6.1.4.1.311.60.2.1.2=Massachusetts, OID.1.3.6.1.4.1.311.60.2.1.3=US
14-11-2023 3:19:33 PM - 		[Issuer]        : CN=.NET Foundation Projects Code Signing CA2, O=.NET Foundation, C=US
14-11-2023 3:19:33 PM - 		[Serial Number] : 019942863FE5B0604A68CA910822A464
14-11-2023 3:19:33 PM - 		[Not Before]    : 30-09-2022 10:00:00 AM
14-11-2023 3:19:33 PM - 		[Not After]     : 02-10-2025 9:59:59 AM
14-11-2023 3:19:33 PM - 		[Thumbprint]    : E8DCDBA58EA28EC94F40E5882D474780DA1BA0C8
14-11-2023 3:19:33 PM - 	Supported Products : 
14-11-2023 3:19:33 PM - 		Microsoft.VisualStudio.Pro
14-11-2023 3:19:33 PM - 			Version : [15.0,17.0)
14-11-2023 3:19:33 PM - 			ProductArchitecture : x86
14-11-2023 3:19:33 PM - 		Microsoft.VisualStudio.Community
14-11-2023 3:19:33 PM - 			Version : [15.0,17.0)
14-11-2023 3:19:33 PM - 			ProductArchitecture : x86
14-11-2023 3:19:33 PM - 		Microsoft.VisualStudio.Enterprise
14-11-2023 3:19:33 PM - 			Version : [15.0,17.0)
14-11-2023 3:19:33 PM - 			ProductArchitecture : x86
14-11-2023 3:19:33 PM - 	References         : 
14-11-2023 3:19:33 PM - 	Prerequisites      : 
14-11-2023 3:19:33 PM - 		-------------------------------------------------------
14-11-2023 3:19:33 PM - 		Identifier   : Microsoft.VisualStudio.Component.CoreEditor
14-11-2023 3:19:33 PM - 		Name         : Visual Studio core editor
14-11-2023 3:19:33 PM - 		Version      : [15.0,17.0)
14-11-2023 3:19:33 PM - Signature Details...
14-11-2023 3:19:33 PM - 	Extension is signed with a valid signature.
14-11-2023 3:19:33 PM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\Services\ExtensionService.cs:line 186
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\Services\ExtensionService.cs:line 28
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\Services\ExtensionPackService.cs:line 101
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\Services\ExtensionPackService.cs:line 42
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported) in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\App.xaml.cs:line 272
   at VSIXInstaller.App.Initialize() in D:\a\_work\1\s\src\product\extensionManager\installer\VSIXInstaller\App.xaml.cs:line 230
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

**Comment by xuzhg** [comment]
It could be related to #374.
